name: 'dbt_monitorial_datagovernance'
version: '0.1.0'
config-version: 2

require-dbt-version: [">=1.9.0", "<2.0.0"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]
macro-paths: ["macros"]

